apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-33
  labels:
    load-test: 'true'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: in-cluster
  project: default
  source:
    chart: k8s-resources
    repoURL: https://charts.deliveryhero.io/
    targetRevision: "0.6.5"
    helm:
      values: |
        Secrets:
          - name: secret01
            fullnameOverride: ""
            annotations: {}
            extraLabels: {}
            tplB64Keys:
              key1: '{{ randAlphaNum 20 | b64enc }}'
            b64Keys:
              key2: value1
            keys:
              key3: dmFsdWUyCg==
          - name: secret02
            fullnameOverride: ""
            annotations: {}
            extraLabels: {}
            tplB64Keys:
              key1: '{{ randAlphaNum 20 | b64enc }}'
            b64Keys:
              key2: value1
            keys:
              key3: dmFsdWUyCg==
          - name: secret03
            fullnameOverride: ""
            annotations: {}
            extraLabels: {}
            tplB64Keys:
              key1: '{{ randAlphaNum 20 | b64enc }}'
            b64Keys:
              key2: value1
            keys:
              key3: dmFsdWUyCg==
          - name: secret04
            fullnameOverride: ""
            annotations: {}
            extraLabels: {}
            tplB64Keys:
              key1: '{{ randAlphaNum 20 | b64enc }}'
            b64Keys:
              key2: value1
            keys:
              key3: dmFsdWUyCg==
          - name: secret05
            fullnameOverride: ""
            annotations: {}
            extraLabels: {}
            tplB64Keys:
              key1: '{{ randAlphaNum 20 | b64enc }}'
            b64Keys:
              key2: value1
            keys:
              key3: dmFsdWUyCg==
          - name: secret06
            fullnameOverride: ""
            annotations: {}
            extraLabels: {}
            tplB64Keys:
              key1: '{{ randAlphaNum 20 | b64enc }}'
            b64Keys:
              key2: value1
            keys:
              key3: dmFsdWUyCg==
          - name: secret07
            fullnameOverride: ""
            annotations: {}
            extraLabels: {}
            tplB64Keys:
              key1: '{{ randAlphaNum 20 | b64enc }}'
            b64Keys:
              key2: value1
            keys:
              key3: dmFsdWUyCg==
          - name: secret08
            fullnameOverride: ""
            annotations: {}
            extraLabels: {}
            tplB64Keys:
              key1: '{{ randAlphaNum 20 | b64enc }}'
            b64Keys:
              key2: value1
            keys:
              key3: dmFsdWUyCg==
          - name: secret09
            fullnameOverride: ""
            annotations: {}
            extraLabels: {}
            tplB64Keys:
              key1: '{{ randAlphaNum 20 | b64enc }}'
            b64Keys:
              key2: value1
            keys:
              key3: dmFsdWUyCg==
          - name: secret10
            fullnameOverride: ""
            annotations: {}
            extraLabels: {}
            tplB64Keys:
              key1: '{{ randAlphaNum 20 | b64enc }}'
            b64Keys:
              key2: value1
            keys:
              key3: dmFsdWUyCg==
  syncPolicy:
    automated: {}
