apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app26
  labels:
    load-test: 'true'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: 03795-sebastiaan-playground
  project: default
  source:
    kustomize:
      namePrefix: app26
    path: kustomize-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
  syncPolicy:
    automated: {}
